config/routes.rb
Rails.application.routes.draw do
  resources :images
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/image.rb
class Image < ApplicationRecord

  	dragonfly_accessor :photo 

	before_save  :shorten_url
	

	def shorten_url
	   chars = [0..9, "A".."Z", 'a'..'z'].map { |range| range.to_a }.flatten
	   self.url =  6.times.map { chars.sample }.join
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/images_controller.rb
class ImagesController < ApplicationController
  before_action :set_image, only: [:show, :edit, :update, :destroy]

  # GET /images
  # GET /images.json
  def index
    @images = Image.all
  end

  # GET /images/1
  # GET /images/1.json
  def show
  end

  # GET /images/new
  def new
    @image = Image.new
  end

  # GET /images/1/edit
  def edit
  end

  # POST /images
  # POST /images.json
  def create
    @image = Image.new(image_params)
      
    @image.photo_url =  @image.url
    respond_to do |format|
      if @image.save
        format.html { redirect_to images_path, notice: 'Image was successfully created.' }
        format.json { render :show, status: :created, location: @image }
      else
        format.html { render :new }
        format.json { render json: @image.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /images/1
  # PATCH/PUT /images/1.json
  def update
    respond_to do |format|
      if @image.update(image_params)
        format.html { redirect_to @image, notice: 'Image was successfully updated.' }
        format.json { render :show, status: :ok, location: @image }
      else
        format.html { render :edit }
        format.json { render json: @image.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /images/1
  # DELETE /images/1.json
  def destroy
    @image.destroy
    respond_to do |format|
      format.html { redirect_to images_url, notice: 'Image was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_image
      @image = Image.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def image_params
      params.require(:image).permit(:url, :height, :width, :photo, :photo_uid )
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/views/images/_form.html.erb
<%= form_for(image) do |f| %>
  <% if image.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(image.errors.count, "error") %> prohibited this image from being saved:</h2>

      <ul>
      <% image.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


<form class= "form-inline">
  <div class="form-group">
    <label for="email">URL:</label>
    <%= f.text_field :url, class: "form-control" %>
  </div>
  <div class="form-group">
    <label for="height">Max Height:</label>
    <%= f.number_field :height, class: "form-control", min: "0" %>
  </div>
  <div class="form-group">
    <label for="width">Max Width:</label>
    <%= f.number_field :width, class: "form-control", min: "0" %>
  </div>
  <button type="submit" class="btn btn-success disable btn-block">Submit</button>
</form>

</br>

<% end %>

app/views/images/edit.html.erb
<h1>Editing Image</h1>

<%= render 'form', image: @image %>

<%= link_to 'Show', @image %> |
<%= link_to 'Back', images_path %>

app/views/images/index.html.erb
<div class="table-responsive">          

<table class="table">
    <thead>
      <tr>
        <th>URL</th>
        <th>Max Height</th>
        <th>Max Width</th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      <% @images.each do |image| %>
      <tr>


        <td><%= link_to image_url(image.url), asset_url(image.photo.thumb("#{image.height}x#{image.width}>").url) if image.photo_stored? %></td>


	
        <td> <%= image.height %></td>
        <td> <%= image.width %> </td>
	<td> <%= button_to 'Destroy', image, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger" %>  </td>

      </tr>
      <% end %>
    </tbody>
  </table>
<br>


<%= button_to 'New URL', new_image_path, method: :get, class: "btn btn-primary" %>  
</div>

app/views/images/new.html.erb
<h2 class="text-center">New URL</h2>

<%= render 'form', image: @image %>

<%= button_to 'Back', images_path, method: :get, class: "btn btn-primary" %>

app/views/images/show.html.erb
<p>
  <% cache @image.avatar do %>
      <%= image_tag @image.avatar.url(:user_defined) %>
  <% end %>
</p>

<%= button_to 'Back', images_path, method: :get, class: "btn btn-primary"%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ImageResizer</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
        <% flash.each do |name, msg| %>
            <%= content_tag(:div, msg, class: "alert alert-info") %>
        <% end %>
        <%= yield %>
    </div>
  </body>
</html>